name: chat_ai_flutter_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  firebase_core: ^4.2.0
  flutter:
    sdk: flutter
  google_generative_ai: ^0.4.7
  shared_preferences: ^2.5.3
  uuid: ^4.5.1
  provider: ^6.1.5+1
  flutter_dotenv: ^5.2.1
  cloud_firestore: ^6.0.3
  markdown_widget: ^2.3.2+8
  flutter_spinkit: ^5.2.2
  firebase_analytics: ^12.0.3
  firebase_crashlytics: ^5.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
